### Сохранение нового документа
POST http://localhost:8080/documents
Content-Type: application/json

{
  "name": "Test Rest 1",
  "text": "Rest text {19} add more text {+100500}  {-127} {helloWorld}"
}

### Просмотр документа по id
GET http://localhost:8080/documents/1

### Просмотр всего списка страниц
GET http://localhost:8080/documents

### Пагинация работает через добавление к списку страниц  ?page={номер страницы}

### Просмотр второй страницы
GET http://localhost:8080/documents?page=2

### Фильтрация работает через добавление к списку страниц  ?filter={тип фильтра}&code={код} Типы филтрации:
### equals - Для просмотра документов, содержащих код, равный code
### less - Для просмотра документов, содержащих код, меньше code
### greater - Для просмотра документов, содержащих код, больше code

### Просмотр списка документов, имеющих коды равные code
GET http://localhost:8080/documents?filter=equals&code=4

### Просмотр списка документов, имеющих коды меньше code
GET http://localhost:8080/documents?filter=less&code=-80000

### Просмотр списка документов, имеющих коды больше code
GET http://localhost:8080/documents?filter=greater&code=100000